//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodexMinning.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public string ERROR_NUMBER { get; set; }
        public string ERROR_SEVERITY { get; set; }
        public string ERROR_STATE { get; set; }
        public string ERROR_PROCEDURE { get; set; }
        public string ERROR_LINE { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public System.DateTime addedon { get; set; }
        public string Process { get; set; }
    }
}
