//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodexMinning.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_GetUsers
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Organization { get; set; }
        public string CountryName { get; set; }
        public string Status { get; set; }
        public string BackgroundColor { get; set; }
    }
}
